"""create runbooks and runbook_sections tables

Revision ID: 78b3d42abdf4
Revises: dd1a51535d13
Create Date: 2026-10-06 12:24:41.065120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78b3d42abdf4'
down_revision: Union[str, Sequence[str], None] = 'dd1a51535d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runbooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=True),
    sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runbooks_service'), 'runbooks', ['service'], unique=False)
    op.create_table('runbook_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('runbook_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['runbook_id'], ['runbooks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runbook_sections_runbook_id'), 'runbook_sections', ['runbook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runbook_sections_runbook_id'), table_name='runbook_sections')
    op.drop_table('runbook_sections')
    op.drop_index(op.f('ix_runbooks_service'), table_name='runbooks')
    op.drop_table('runbooks')
    # ### end Alembic commands ###
