"""create credentials and llm_step_configs tables

Revision ID: be8386130456
Revises: 78b3d42abdf4
Create Date: 2026-10-06 18:43:02.904701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be8386130456'
down_revision: Union[str, Sequence[str], None] = '78b3d42abdf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('encrypted_payload', sa.Text(), nullable=False),
    sa.Column('preview', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('purpose')
    )
    op.create_table('llm_step_configs',
    sa.Column('step_key', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=120), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_output_tokens', sa.Integer(), nullable=True),
    sa.Column('credential_purpose', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credential_purpose'], ['credentials.purpose'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('step_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_step_configs')
    op.drop_table('credentials')
    # ### end Alembic commands ###
